baseURL = "https://example.com"
languageCode = "en-us"
theme = "MorningPages"

title = "Morning Pages"
description = "Journaling is like whispering to one's self and listening at the same time."

DefaultContentLanguage = "en"
pygmentsUseClasses = true

disableKinds = ["section", "taxonomyTerm", "pages"]

googleAnalytics = "UA-XXXXXXXXX-X"

# Enable JUST series taxonomy
[taxonomies]
  series = "series"

# Forcing slug to appear after the books
[permalinks]
  books = "/books/:slug/"

[author]
  name = "Your name"
  shortname = "scriptstar"
  homepage = "https://twitter.com/scriptstar/"

[params]
mainSections = ["books"]

headTitle = "Morning Pages"
description = "Journaling is like whispering to one's self and listening at the same time."
tagline = "I #journal 3 positive things, every day"

# Setup a netlify account to make this work.
# Look implementation deatials inside themes readme.md file
bookAPI = "https://example.com/.netlify/functions/getBookDetails"

extraHead = ''
postFooterContent = ''
postHeaderContent = ''

themeColor = "#fff" # Theme color displayed on mobile browsers

facebookSite = ""
twitterSite = ""
socialProfiles = ["https://twitter.com/scriptstar","https://www.linkedin.com/in/narendraman/","https://github.com/scriptstar/","https://facebook.com/scriptstar/"]

alternatePageName = "Morning Pages"
organizationLogo = "/logo.png"
organizationName = "5PagesADay.com"

publisherName = "Morning Pages"
publisherLogo = "/logo.png"
publisherLogoWidth = 600
publisherLogoHeight = 60

[[params.headerPage]]
name = "Start Here"
link = "start"

[[params.headerPage]]
name = "My Tools"
link = "resources"

[[params.socials]]
name = "Who Am I?"
link = "http://twitter.com/scriptstar"

[[params.socials]]
name = "Subscribe"
link = "https://sendfox.com/naren"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[markup]
  defaultMarkdownHandler = "blackfriday"